<a href="https://colab.research.google.com/github/prasunamishra/5CS037/blob/main/Week1_Prasuna.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#Problem-1 Array Creation
#1
import numpy as np
empty_array = np.empty((2, 2))
print(empty_array)
#2
ones_array = np.ones((4, 2))
print("\n One array is:")
print(ones_array)
#3
filled_array = np.full((3, 3),3 , dtype=int)
print("\nArray Filled :")
print(filled_array)
#4
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.zeros_like(a)
print(b)
#5
b = np.ones_like(a)
print(b)
#6
new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print(np_array)

[[2.14539766e-315 0.00000000e+000]
 [6.71058800e-310 6.71058800e-310]]

 One array is:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array Filled :
[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[1 2 3 4]


In [21]:
#Problem - 2: Array Manipulation
#1
import numpy as np
array = np.arange(10, 50)
print(array)
#2
matrix = np.arange(9).reshape(3, 3)
print(matrix)
#3
identity_matrix = np.eye(3)
print(identity_matrix)
#4
rand_arr = np.random.random(30)
print("Mean is:", rand_arr.mean())
#5
arr_10x10 = np.random.random((10, 10))
print("Minimum value:", arr_10x10.min())
print("Maximum value:", arr_10x10.max())
#6
A = np.zeros(10)
A[4] = 1
print(A)
#7
array = np.array([1, 2, 0, 0, 4, 0])
reverse = array[::-1]
print(reverse)
#8
border = np.ones((5, 5))
border[1:-1, 1:-1] = 0
print(border)
#9
checker = np.zeros((8, 8))
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print(checker)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean is: 0.5032618006924366
Minimum value: 0.005475051515485552
Maximum value: 0.9772348238164374
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [41]:
#Problem - 3: Array Operations
import numpy as np
x = np.array([[1, 2],
              [3, 5]])
y = np.array([[5, 6],
              [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
#1
add_xy = x + y
print(add_xy)
#2
sub_xy = x - y
print(sub_xy)
#3
mul_x = x * 3
print(mul_x)
#4
square_x = x ** 2
print(square_x)
square_y = y ** 2
print(square_y)
square_v = v ** 2
print(square_v)
square_w = w ** 2
print(square_w)
#5
dot_vw = np.dot(v, w)
print(dot_vw)
dot_xv = np.dot(x, v)
print(dot_xv)
dot_xy = np.dot(x, y)
print(dot_xy)
#6
concat_xy_rows = np.concatenate((x, y), axis=0)
print(concat_xy_rows)
vw_col = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)
print(vw_col)
#7
#np.concatenate((x, v))
#Yes, if we do this then we get the error i.e. ValueError:all the input array dimensions except for the concatenation axis must match exactly







[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [52]:
#Problem - 4: Matrix Operations
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
#1
A_inv = np.linalg.inv(A)
result = A.dot(A_inv)
print(result)
#2
AB = A.dot(B)
BA = B.dot(A)
print("AB =\n", AB)
print("BA =\n", BA)
print("Are AB and BA equal? ->", np.array_equal(AB,BA))
#3
left = (A.dot(B)).T
right = B.T.dot(A.T)
print("Left side =\n", left)
print("Right side =\n", right)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Are AB and BA equal? -> False
Left side =
 [[23 51]
 [13 29]]
Right side =
 [[23 51]
 [13 29]]


In [54]:
#• Solve the following system of Linear equation using Inverse Methods.
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
import numpy as np
A = np.array([
    [ 2, -3,  1],
    [ 1, -1,  2],
    [ 3,  1, -1]
])
B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = A_inv.dot(B)
print(X)


[ 2.  1. -2.]


In [58]:
#• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}
import numpy as np
A_inv = np.linalg.inv(A)
X = A_inv.dot(B)
print("Value of  (x, y, z):", X)


Value of  (x, y, z): [ 2.  1. -2.]


In [60]:
import numpy as np
import time

#ADDITION
# Python lists
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))
start = time.time()
list_add = [list1[i] + list2[i] for i in range(1_000_000)]
end = time.time()
print("Python List Addition Time:", end - start, "seconds")
# NumPy arrays
arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)
start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("NumPy Array Addition Time:", end - start, "seconds")

#MULTIPLICATION
# Python lists
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(1_000_000)]
end = time.time()
print("Python List Multiplication Time:", end - start, "seconds")
# NumPy arrays
start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("NumPy Array Multiplication Time:", end - start, "seconds")

#DOT PRODUCT
# Python lists
start = time.time()
dot_py = sum(list1[i] * list2[i] for i in range(1_000_000))
end = time.time()
print("Python List Dot Product Time:", end - start, "seconds")
# NumPy arrays
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print("NumPy Dot Product Time:", end - start, "seconds")

#MATRIX MULTIPLICATION
# Python lists
M1 = [[i for i in range(1000)] for _ in range(1000)]
M2 = [[i for i in range(1000)] for _ in range(1000)]
start = time.time()
# matrix multiplication using python
result_py = [[sum(M1[i][k] * M2[k][j] for k in range(1000))
              for j in range(1000)]
              for i in range(1000)]
end = time.time()
print("Python List Matrix Multiplication Time:", end - start, "seconds")

# NumPy arrays
A = np.arange(1_000_000).reshape(1000, 1000)
B = np.arange(1_000_000).reshape(1000, 1000)
start = time.time()
result_np = np.dot(A, B)
end = time.time()
print("NumPy Matrix Multiplication Time:", end - start, "seconds")


Python List Addition Time: 0.1546337604522705 seconds
NumPy Array Addition Time: 0.00423431396484375 seconds
Python List Multiplication Time: 0.1305088996887207 seconds
NumPy Array Multiplication Time: 0.004118919372558594 seconds
Python List Dot Product Time: 0.11816763877868652 seconds
NumPy Dot Product Time: 0.0019109249114990234 seconds
Python List Matrix Multiplication Time: 189.7116003036499 seconds
NumPy Matrix Multiplication Time: 2.0511298179626465 seconds
